### ISSUE TITLE
Nothing is clickable on mobile

### ISSUE THREAD

**Issue by biko-the-bird** [CrypTools/cryptools.github.io#11]
I am unable to click any interface elements (navbar menu, buttons, etc). I am using iOS 11 on safari.

**Comment by arguiot** [comment]
Thank you very much for reporting, we’ll try to fix it. If you have any information such as trace or error code, you can post it here, it will help us fixing the bug.

**Comment by arguiot** [comment]
@biko-the-bird Does the bug persist after restarting your device? Because I tried on my iPhone 7 and on my iPad Mini 2 (both on iOS 11) and I couldn’t reproduce this bug.

**Comment by biko-the-bird** [comment]
Yes restarting the device has solved the problem. Thank you for intervening.

**Comment by arguiot** [comment]
@biko-the-bird Ok, I’ll try to fix the bug, but I can’t really promise anything, because I’m unable to reproduce it for the moment. I keep this issue open, just to know if anyone has the same issue.

I’ll post here if there are any updates.

**Comment by arguiot** [comment]
@biko-the-bird Could you send me a screenshot of the regulatory & about section (`Settings > general > about` and `Settings > general > Regulatory`), like this:
![img_0512](https://user-images.githubusercontent.com/18022260/37871608-68434c4c-3024-11e8-9887-c85d6646b867.png)
![img_0513](https://user-images.githubusercontent.com/18022260/37871609-686f99a0-3024-11e8-8e94-7d8c76027f07.png)
So I can try to reproduce this issue.

**Comment by biko-the-bird** [comment]
I’m sorry if I wasn’t clear before. I can’t recreate the issue on my device any more. Everything on your site works perfectly now.

**Comment by arguiot** [comment]
Great 👍. Thank you for your patience.
